### ISSUE TITLE
Run project

### ISSUE THREAD

**Issue by jmuziki** [skellock/expo-with-ignite#1]
Hi this looks really nifty! Having some trouble running the project locally though. Ran the following commands:

1. `Git clone`
2. `npm install` in project directory
3. `npm start` in project directory 

This gives me the following npm errors

![screen shot 2017-05-05 at 12 12 12 pm](https://cloud.githubusercontent.com/assets/7222660/25741679/26468d0a-318c-11e7-9246-48e67bc9dc6a.png)

Please advise?

**Comment by skellock** [comment]
Ya, this isn't a project you can clone & run because it requires Expo to run it, and you'll need your own config.

This is, rather just a project you can look at for reference.   Was an experiment to see if I could get the two to play together.

So if you:
* start with your own Expo-built app
* add the same npm dependencies from this package.json
* copy the `App` and `ignite` directories
* copy the `main.js`.

You'll be ready to go!

Lemme know if you give it a try.
